config/routes.rb
Donorsystem::Application.routes.draw do
  resources :partners

  get "welcome/index"

  get "login/new"

  resources :villagesummaryreports

  resources :villageinfos

  resources :donorvillages

  resources :donorinfos

  resources :villageusers

  resources :blockusers do
     resources :villageusers
  end 

  resources :villages

  resources :blocks do
	resources :blockusers
  end

  post "login/signin"

  get "login/signout"

  resources :districts

  resources :users

  root :to => "login#new"

  

end

app/models/villagesummaryreport.rb
class Villagesummaryreport < ActiveRecord::Base
  belongs_to :village
end

app/controllers/villagesummaryreports_controller.rb
class VillagesummaryreportsController < ApplicationController
  before_filter :login_required
  before_action :set_villagesummaryreport, only: [:show, :edit, :update, :destroy]

  # GET /villagesummaryreports
  # GET /villagesummaryreports.json
  def index
    @villagesummaryreports = Villagesummaryreport.all
  end

  # GET /villagesummaryreports/1
  # GET /villagesummaryreports/1.json
  def show
  end

  # GET /villagesummaryreports/new
  def new
    @villagesummaryreport = Villagesummaryreport.new
  end

  # GET /villagesummaryreports/1/edit
  def edit
  end

  # POST /villagesummaryreports
  # POST /villagesummaryreports.json
  def create
    @villagesummaryreport = Villagesummaryreport.new(villagesummaryreport_params)

    respond_to do |format|
      if @villagesummaryreport.save
        format.html { redirect_to @villagesummaryreport, notice: 'Villagesummaryreport was successfully created.' }
        format.json { render action: 'show', status: :created, location: @villagesummaryreport }
      else
        format.html { render action: 'new' }
        format.json { render json: @villagesummaryreport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /villagesummaryreports/1
  # PATCH/PUT /villagesummaryreports/1.json
  def update
    respond_to do |format|
      if @villagesummaryreport.update(villagesummaryreport_params)
        format.html { redirect_to @villagesummaryreport, notice: 'Villagesummaryreport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @villagesummaryreport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /villagesummaryreports/1
  # DELETE /villagesummaryreports/1.json
  def destroy
    @villagesummaryreport.destroy
    respond_to do |format|
      format.html { redirect_to villagesummaryreports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_villagesummaryreport
      @villagesummaryreport = Villagesummaryreport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def villagesummaryreport_params
      params.require(:villagesummaryreport).permit(:village_id, :children_enrolled, :children_attended, :class_working_days, :current_cpi, :activities_html, :start_date, :end_date)
    end
end

app/helpers/villagesummaryreports_helper.rb
module VillagesummaryreportsHelper
end

app/views/villagesummaryreports/_form.html.erb
<%= form_for(@villagesummaryreport) do |f| %>
  <% if @villagesummaryreport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@villagesummaryreport.errors.count, "error") %> prohibited this villagesummaryreport from being saved:</h2>

      <ul>
      <% @villagesummaryreport.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :village %><br>
    <%= f.text_field :village %>
  </div>
  <div class="field">
    <%= f.label :children_enrolled %><br>
    <%= f.number_field :children_enrolled %>
  </div>
  <div class="field">
    <%= f.label :children_attended %><br>
    <%= f.number_field :children_attended %>
  </div>
  <div class="field">
    <%= f.label :class_working_days %><br>
    <%= f.number_field :class_working_days %>
  </div>
  <div class="field">
    <%= f.label :current_cpi %><br>
    <%= f.number_field :current_cpi %>
  </div>
  <div class="field">
    <%= f.label :activities_html %><br>
    <%= f.text_field :activities_html %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/villagesummaryreports/edit.html.erb
<h1>Editing villagesummaryreport</h1>

<%= render 'form' %>

<%= link_to 'Show', @villagesummaryreport %> |
<%= link_to 'Back', villagesummaryreports_path %>

app/views/villagesummaryreports/index.html.erb
<h1>Listing villagesummaryreports</h1>

<table>
  <thead>
    <tr>
      <th>Village</th>
      <th>Children enrolled</th>
      <th>Children attended</th>
      <th>Class working days</th>
      <th>Current cpi</th>
      <th>Activities html</th>
      <th>Start date</th>
      <th>End date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @villagesummaryreports.each do |villagesummaryreport| %>
      <tr>
        <td><%= villagesummaryreport.village %></td>
        <td><%= villagesummaryreport.children_enrolled %></td>
        <td><%= villagesummaryreport.children_attended %></td>
        <td><%= villagesummaryreport.class_working_days %></td>
        <td><%= villagesummaryreport.current_cpi %></td>
        <td><%= villagesummaryreport.activities_html %></td>
        <td><%= villagesummaryreport.start_date %></td>
        <td><%= villagesummaryreport.end_date %></td>
        <td><%= link_to 'Show', villagesummaryreport %></td>
        <td><%= link_to 'Edit', edit_villagesummaryreport_path(villagesummaryreport) %></td>
        <td><%= link_to 'Destroy', villagesummaryreport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Villagesummaryreport', new_villagesummaryreport_path %>

app/views/villagesummaryreports/new.html.erb
<h1>New villagesummaryreport</h1>

<%= render 'form' %>

<%= link_to 'Back', villagesummaryreports_path %>

app/views/villagesummaryreports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Village:</strong>
  <%= @villagesummaryreport.village %>
</p>

<p>
  <strong>Children enrolled:</strong>
  <%= @villagesummaryreport.children_enrolled %>
</p>

<p>
  <strong>Children attended:</strong>
  <%= @villagesummaryreport.children_attended %>
</p>

<p>
  <strong>Class working days:</strong>
  <%= @villagesummaryreport.class_working_days %>
</p>

<p>
  <strong>Current cpi:</strong>
  <%= @villagesummaryreport.current_cpi %>
</p>

<p>
  <strong>Activities html:</strong>
  <%= @villagesummaryreport.activities_html %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @villagesummaryreport.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @villagesummaryreport.end_date %>
</p>

<%= link_to 'Edit', edit_villagesummaryreport_path(@villagesummaryreport) %> |
<%= link_to 'Back', villagesummaryreports_path %>