config/routes.rb
Donorsystem::Application.routes.draw do
  resources :partners

  get "welcome/index"

  get "login/new"

  resources :villagesummaryreports

  resources :villageinfos

  resources :donorvillages

  resources :donorinfos

  resources :villageusers

  resources :blockusers do
     resources :villageusers
  end 

  resources :villages

  resources :blocks do
	resources :blockusers
  end

  post "login/signin"

  get "login/signout"

  resources :districts

  resources :users

  root :to => "login#new"

  

end

app/models/donorvillage.rb
class Donorvillage < ActiveRecord::Base
  belongs_to :village, foreign_key: "village_id", class_name: "Village"
  belongs_to :user, foreign_key: "user_id", class_name: "User"
  validates_presence_of :user_id
  include ApplicationHelper



end

app/controllers/donorvillages_controller.rb
class DonorvillagesController < ApplicationController
  before_filter :login_required
  before_action :set_donorvillage, only: [:show, :edit, :update, :destroy]
  before_action :load_arrays
  include ApplicationHelper

  # GET /donorvillages
  # GET /donorvillages.json
  def index
    @donorvillages = Donorvillage.all
  end

  # GET /donorvillages/1
  # GET /donorvillages/1.json
  def show
  end

  # GET /donorvillages/new
  def new
    @donorvillage = Donorvillage.new
  end

  # GET /donorvillages/1/edit
  def edit
  end

  # POST /donorvillages
  # POST /donorvillages.json
  def create
    @donorvillage = Donorvillage.new(donorvillage_params)

    respond_to do |format|
      if @donorvillage.save
        format.html { redirect_to @donorvillage, notice: 'Donorvillage was successfully created.' }
        format.json { render action: 'show', status: :created, location: @donorvillage }
      else
        format.html { render action: 'new' }
        format.json { render json: @donorvillage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donorvillages/1
  # PATCH/PUT /donorvillages/1.json
  def update
    respond_to do |format|
      if @donorvillage.update(donorvillage_params)
        format.html { redirect_to @donorvillage, notice: 'Donorvillage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @donorvillage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donorvillages/1
  # DELETE /donorvillages/1.json
  def destroy
    @donorvillage.destroy
    respond_to do |format|
      format.html { redirect_to donorvillages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donorvillage
      @donorvillage = Donorvillage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donorvillage_params
      params.require(:donorvillage).permit(:village_id, :user_id, :start_date, :end_date, :amount_for_village, :status)
    end

    def load_arrays
	@villages = Village.where('status = ?', Status::Active)

	@donors = User.where('status = :status and role = :role and id in (:id)', { status: Status::Active, role: Role::Donor, id: Donorinfo.all.collect(&:user_id) } )
    end
end

app/helpers/donorvillages_helper.rb
module DonorvillagesHelper
end

app/views/donorvillages/_form.html.erb
<%= form_for(@donorvillage) do |f| %>
  <% if @donorvillage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donorvillage.errors.count, "error") %> prohibited this donorvillage from being saved:</h2>

      <ul>
      <% @donorvillage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :village %><br>
    <%= f.collection_select :village_id, @villages, :id, :name, :include_blank => "Select a village" %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.collection_select :user_id, @donors, :id, :name, :include_blank => "Select a donor" %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_field :end_date %>
  </div>
  <div class="field">
    <%= f.label :amount_for_village %><br>
    <%= f.text_field :amount_for_village %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donorvillages/edit.html.erb
<h1>Editing donorvillage</h1>

<%= render 'form' %>

<%= link_to 'Show', @donorvillage %> |
<%= link_to 'Back', donorvillages_path %>

app/views/donorvillages/index.html.erb
<h1>Listing donorvillages</h1>

<table>
  <thead>
    <tr>
      <th>Village</th>
      <th>User</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Amount for village</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @donorvillages.each do |donorvillage| %>
      <tr>
        <td><%= donorvillage.village %></td>
        <td><%= donorvillage.user %></td>
        <td><%= donorvillage.start_date %></td>
        <td><%= donorvillage.end_date %></td>
        <td><%= donorvillage.amount_for_village %></td>
        <td><%= donorvillage.status %></td>
        <td><%= link_to 'Show', donorvillage %></td>
        <td><%= link_to 'Edit', edit_donorvillage_path(donorvillage) %></td>
        <td><%= link_to 'Destroy', donorvillage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donorvillage', new_donorvillage_path %>

app/views/donorvillages/new.html.erb
<h1>New donorvillage</h1>

<%= render 'form' %>

<%= link_to 'Back', donorvillages_path %>

app/views/donorvillages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Village:</strong>
  <%= @donorvillage.village %>
</p>

<p>
  <strong>User:</strong>
  <%= @donorvillage.user %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @donorvillage.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @donorvillage.end_date %>
</p>

<p>
  <strong>Amount for village:</strong>
  <%= @donorvillage.amount_for_village %>
</p>

<p>
  <strong>Status:</strong>
  <%= @donorvillage.status %>
</p>

<%= link_to 'Edit', edit_donorvillage_path(@donorvillage) %> |
<%= link_to 'Back', donorvillages_path %>