config/routes.rb
Donorsystem::Application.routes.draw do
  resources :partners

  get "welcome/index"

  get "login/new"

  resources :villagesummaryreports

  resources :villageinfos

  resources :donorvillages

  resources :donorinfos

  resources :villageusers

  resources :blockusers do
     resources :villageusers
  end 

  resources :villages

  resources :blocks do
	resources :blockusers
  end

  post "login/signin"

  get "login/signout"

  resources :districts

  resources :users

  root :to => "login#new"

  

end

app/views/shared/_logo.html.erb
<h1 class="span5 pull-left">
<%=  image_tag "eurekachild.gif",  :alt => "Eureka AID India" %>
</h1>

app/views/shared/_menu.html.erb
<% if (controller.action_name == "index") %>
<aside class="span3 leftNavs">
<% if (controller.current_user.role == 1) %>
  <h2>Manage</h2>
  <ul>
  	<li>
		<%= link_to districts_path do %>
		  <%= image_tag('/images/spacer.gif', :class => "icon_district") %> District
		<% end %>				
	</li>
	<li>
		<%= link_to blocks_path do %>
		  <%= image_tag('/images/spacer.gif', :class => "icon_block") %> Block
		<% end %>
	</li>
	<li>
		<%= link_to villages_path do %>
		  <%= image_tag('/images/spacer.gif', :class => "icon_village") %> Village
		<% end %>
	</li>
	<li>
		<%= link_to users_path do %>
		  <%= image_tag('/images/spacer.gif', :class => "icon_users") %> User
		<% end %>		
	</li>
	<li>
		<%= link_to donorinfos_path do %>
		  <%= image_tag('/images/spacer.gif', :class => "icon_donors") %> Donors
		<% end %>		
	</li>	
	<li>
		<%= link_to partners_path do %>
		  <%= image_tag('/images/spacer.gif', :class => "icon_partners") %> Partners
		<% end %>		
	</li>	
</ul>
<% end %>
</aside>
<% end %>

app/views/shared/_modal.html.erb
<% 
   @pathToReturn = request.fullpath
%>

<div class="popupHolder" id = "modal">
    <header class="popup-header row-fluid">
      <div class="closeBtn"><a href="<%= @pathToReturn %>">X</a></div>
      <div class="span6">
        <p class="popup-backlinks">&nbsp;</p>
        <h2 class="popup-title"></h2>
      </div>
    </header>
    <section  id="modal-body" class="popup-content">
    </section>
    <footer class="popup-footer">
	<%= link_to @pathToReturn , :class=>"btnGray" do %>
	   <%= image_tag('/images/spacer.gif', :class =>"icon_delete") %> Cancel
	<% end %> 
	<%= link_to :class=>"btnGreen", :onclick=> "$('form').submit()" do %>
	   <%= image_tag('/images/spacer.gif', :class =>"icon_tick") %> Done
	<% end %>
     </footer>
</div>
<div id="modal-container" />

app/views/shared/_userinfo.html.erb
<div class="span6 text-right pull-right userDetails">
      <% if (!controller.current_user.nil?) %>
	<div><%= controller.current_user.name %></div>
	<div><%= link_to "Sign out", controller: "login", action: "signout" %></div>
     <% end %>
</div>