config/routes.rb
Donorsystem::Application.routes.draw do
  resources :partners

  get "welcome/index"

  get "login/new"

  resources :villagesummaryreports

  resources :villageinfos

  resources :donorvillages

  resources :donorinfos

  resources :villageusers

  resources :blockusers do
     resources :villageusers
  end 

  resources :villages

  resources :blocks do
	resources :blockusers
  end

  post "login/signin"

  get "login/signout"

  resources :districts

  resources :users

  root :to => "login#new"

  

end

app/models/blockuser.rb
class Blockuser < ActiveRecord::Base
  belongs_to :block, foreign_key: "block_id", class_name: "Block"
  belongs_to :user, foreign_key: "user_id", class_name: "User"
  validates_presence_of :user_id
  include ApplicationHelper

  def villageusers
     @villages = Village.find_all_by_block_id_and_status(self.block_id, Status::Active, :select => "id").map(&:id)

     Villageuser.find_all_by_village_id_and_user_id_and_status(@villages, self.user_id, Status::Active)
  end

end

app/controllers/blockusers_controller.rb
class BlockusersController < ApplicationController
  before_filter :login_required
  before_action :set_blockuser, only: [:show, :edit, :update, :destroy]

  # GET /blockusers
  # GET /blockusers.json
  def index
    @blockusers = Blockuser.all
  end

  # GET /blockusers/1
  # GET /blockusers/1.json
  def show
  end

  # GET /blockusers/new
  def new
    @blockuser = Blockuser.new
  end

  # GET /blockusers/1/edit
  def edit
  end

  # POST /blockusers
  # POST /blockusers.json
  def create
    @blockuser = Blockuser.new(blockuser_params)

    respond_to do |format|
      if @blockuser.save
        format.html { redirect_to @blockuser, notice: 'Blockuser was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blockuser }
      else
        format.html { render action: 'new' }
        format.json { render json: @blockuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blockusers/1
  # PATCH/PUT /blockusers/1.json
  def update
    respond_to do |format|
      if @blockuser.update(blockuser_params)
        format.html { redirect_to @blockuser, notice: 'Blockuser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blockuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blockusers/1
  # DELETE /blockusers/1.json
  def destroy
    @blockuser.destroy
    respond_to do |format|
      format.html { redirect_to blockusers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blockuser
      @blockuser = Blockuser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blockuser_params
      params.require(:blockuser).permit(:block_id, :user_id, :role, :start_date, :end_date, :status)
    end
end

app/helpers/blockusers_helper.rb
module BlockusersHelper
end

app/views/blockusers/_form.html.erb
<%= form_for(@blockuser) do |f| %>
  <% if @blockuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blockuser.errors.count, "error") %> prohibited this blockuser from being saved:</h2>

      <ul>
      <% @blockuser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :block %><br>
    <%= f.text_field :block %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.number_field :role %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blockusers/edit.html.erb
<h1>Editing blockuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @blockuser %> |
<%= link_to 'Back', blockusers_path %>

app/views/blockusers/index.html.erb
<h1>Listing blockusers</h1>

<table>
  <thead>
    <tr>
      <th>Block</th>
      <th>User</th>
      <th>Role</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @blockusers.each do |blockuser| %>
      <tr>
        <td><%= blockuser.block %></td>
        <td><%= blockuser.user %></td>
        <td><%= blockuser.role %></td>
        <td><%= blockuser.start_date %></td>
        <td><%= blockuser.end_date %></td>
        <td><%= blockuser.status %></td>
        <td><%= link_to 'Show', blockuser %></td>
        <td><%= link_to 'Edit', edit_blockuser_path(blockuser) %></td>
        <td><%= link_to 'Destroy', blockuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blockuser', new_blockuser_path %>

app/views/blockusers/new.html.erb
<h1>New blockuser</h1>

<%= render 'form' %>

<%= link_to 'Back', blockusers_path %>

app/views/blockusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Block:</strong>
  <%= @blockuser.block %>
</p>

<p>
  <strong>User:</strong>
  <%= @blockuser.user %>
</p>

<p>
  <strong>Role:</strong>
  <%= @blockuser.role %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @blockuser.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @blockuser.end_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @blockuser.status %>
</p>

<%= link_to 'Edit', edit_blockuser_path(@blockuser) %> |
<%= link_to 'Back', blockusers_path %>